-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bon_achat
(
    id serial NOT NULL,
    numerobon text COLLATE pg_catalog."default" NOT NULL,
    date_emission date NOT NULL DEFAULT CURRENT_DATE,
    fournisseur_id integer NOT NULL,
    vendeur_id integer NOT NULL,
    CONSTRAINT bon_achat_pkey PRIMARY KEY (id),
    CONSTRAINT bon_achat_numerobon_key UNIQUE (numerobon)
);

CREATE TABLE IF NOT EXISTS public.clients
(
    id serial NOT NULL,
    userid integer NOT NULL,
    nom character varying(100) COLLATE pg_catalog."default" NOT NULL,
    prenom character varying(100) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    telephone character varying(20) COLLATE pg_catalog."default",
    adresse text COLLATE pg_catalog."default",
    ville character varying(100) COLLATE pg_catalog."default",
    code_postal character varying(20) COLLATE pg_catalog."default",
    pays character varying(100) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    date_creation timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT clients_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.commande
(
    id serial NOT NULL,
    produit_id integer NOT NULL,
    nom_produit character varying(100) COLLATE pg_catalog."default" NOT NULL,
    quantite integer NOT NULL,
    date_commande date DEFAULT CURRENT_DATE,
    customer_name character varying(255) COLLATE pg_catalog."default",
    userid integer,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'Pending'::character varying,
    CONSTRAINT commande_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.facture
(
    id serial NOT NULL,
    invoice_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    customer_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    client_id integer,
    date date NOT NULL,
    due_date date,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'Draft'::character varying,
    notes text COLLATE pg_catalog."default",
    total_amount numeric(10, 2) NOT NULL,
    user_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT facture_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.facture_items
(
    id serial NOT NULL,
    facture_id integer,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10, 2) NOT NULL,
    amount numeric(10, 2) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT facture_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.fournisseur
(
    id serial NOT NULL,
    nom_entreprise character varying(50) COLLATE pg_catalog."default" NOT NULL,
    num_registre integer NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    tel character varying(25) COLLATE pg_catalog."default" NOT NULL,
    userid integer,
    CONSTRAINT fournisseur_pkey PRIMARY KEY (id),
    CONSTRAINT fournisseur_email_key UNIQUE (email),
    CONSTRAINT fournisseur_num_registre_key UNIQUE (num_registre),
    CONSTRAINT fournisseur_tel_key UNIQUE (tel)
);

CREATE TABLE IF NOT EXISTS public.produit
(
    id serial NOT NULL,
    nom character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    image text COLLATE pg_catalog."default",
    total integer NOT NULL,
    serial_num text COLLATE pg_catalog."default",
    fournisseur_id integer NOT NULL,
    prix integer NOT NULL DEFAULT 0,
    user_id integer,
    CONSTRAINT produit_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.supplier_order
(
    id serial NOT NULL,
    fournisseur_id integer NOT NULL,
    supplier_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    produit_id integer NOT NULL,
    product_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10, 2) NOT NULL,
    total_amount numeric(10, 2) NOT NULL,
    order_date date DEFAULT CURRENT_DATE,
    expected_delivery_date date,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'Pending'::character varying,
    notes text COLLATE pg_catalog."default",
    userid integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT supplier_order_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(100) COLLATE pg_catalog."default",
    password character varying(100) COLLATE pg_catalog."default",
    name character(50) COLLATE pg_catalog."default",
    last_name character(50) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    role character varying(20) COLLATE pg_catalog."default" DEFAULT 'user'::character varying,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vendeur
(
    id serial NOT NULL,
    nom_entreprise character varying(50) COLLATE pg_catalog."default" NOT NULL,
    num_registre integer NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    tel integer NOT NULL,
    CONSTRAINT vendeur_pkey PRIMARY KEY (id),
    CONSTRAINT vendeur_email_key UNIQUE (email),
    CONSTRAINT vendeur_num_registre_key UNIQUE (num_registre),
    CONSTRAINT vendeur_tel_key UNIQUE (tel)
);

ALTER TABLE IF EXISTS public.bon_achat
    ADD CONSTRAINT bon_achat_fournisseur_id_fkey FOREIGN KEY (fournisseur_id)
    REFERENCES public.fournisseur (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.bon_achat
    ADD CONSTRAINT bon_achat_vendeur_id_fkey FOREIGN KEY (vendeur_id)
    REFERENCES public.vendeur (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.clients
    ADD CONSTRAINT clients_userid_fkey FOREIGN KEY (userid)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.commande
    ADD CONSTRAINT commande_produit_id_fkey FOREIGN KEY (produit_id)
    REFERENCES public.produit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.commande
    ADD CONSTRAINT commande_userid_fkey FOREIGN KEY (userid)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.facture
    ADD CONSTRAINT facture_client_id_fkey FOREIGN KEY (client_id)
    REFERENCES public.clients (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.facture_items
    ADD CONSTRAINT facture_items_facture_id_fkey FOREIGN KEY (facture_id)
    REFERENCES public.facture (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.produit
    ADD CONSTRAINT produit_fournisseur_id_fkey FOREIGN KEY (fournisseur_id)
    REFERENCES public.fournisseur (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.produit
    ADD CONSTRAINT produit_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.supplier_order
    ADD CONSTRAINT supplier_order_fournisseur_id_fkey FOREIGN KEY (fournisseur_id)
    REFERENCES public.fournisseur (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_supplier_order_fournisseur_id
    ON public.supplier_order(fournisseur_id);


ALTER TABLE IF EXISTS public.supplier_order
    ADD CONSTRAINT supplier_order_produit_id_fkey FOREIGN KEY (produit_id)
    REFERENCES public.produit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_supplier_order_produit_id
    ON public.supplier_order(produit_id);

END;